name: Check prose and style of docs

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install proselint
      run: |
        python -m pip install proselint
    - name: Run proselint on all md and rst files
      run: |
        python ./utils/run_proselint/main.py
    - uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install alex - checker for inconsiderate / insensitive writing
      run: |
        npm install alex --global
    - name: Run alex on all md and rst files
      run: |
        python ./utils/run_alex/main.py
    - name: Install aspell (spell checker)
      run: |
        sudo apt-get install aspell aspell-en
    - name: Run spell checker on all md and rst files
      run: |
        python ./utils/run_spell_checker/main.py
